title: Training
template: training/show
layout: layout
revisions: false
route: '/training/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: true
  max_depth: 3
